{% set version = "0.6.1" %}

package:
  name: pandas_ml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pandas_ml/pandas_ml-{{ version }}.tar.gz
  sha256: f5d4f7c6eeada8e98856daace511cdc84995b593a3ae2741dcc4e665ec2918d3

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas >=0.17.0,<=0.24.2
    - enum34  # [py2k]

test:
  imports:
    - pandas_ml
    - pandas_ml.confusion_matrix
    - pandas_ml.core
    - pandas_ml.imbaccessors
    - pandas_ml.misc
    - pandas_ml.misc.test
    - pandas_ml.skaccessors
    - pandas_ml.smaccessors
    - pandas_ml.snsaccessors
    - pandas_ml.test
    - pandas_ml.util
    - pandas_ml.xgboost
    
about:
  home: https://github.com/pandas-ml/pandas-ml
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'pandas, scikit-learn and xgboost integration'

  description: |
    pandas_ml is a package which integrates pandas, scikit-learn,
    xgboost into one package for easy handling of data and creation 
    of machine learning models.
  doc_url: http://pandas-ml.readthedocs.org/en/stable
  dev_url: https://github.com/pandas-ml/pandas-ml

extra:
  recipe-maintainers:
    - souravsingh
    - sinhrks
