{% set name = "pandas_ml" %}
{% set version = "0.6.0" %}
{% set sha256 = "43e54b1a6d17ef76c7c7bc64ac2a2a9ef4060e57b920e81a81895897e2cd9125" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pandas >=0.17.0
  run:
    - python
    - pandas >=0.17.0
    - enum34  # [py2k]

test:
  imports:
    - pandas_ml
    - pandas_ml.confusion_matrix
    - pandas_ml.confusion_matrix.test
    - pandas_ml.core
    - pandas_ml.imbaccessors
    - pandas_ml.imbaccessors.test
    - pandas_ml.misc
    - pandas_ml.misc.test
    - pandas_ml.skaccessors
    - pandas_ml.skaccessors.test
    - pandas_ml.smaccessors
    - pandas_ml.smaccessors.test
    - pandas_ml.snsaccessors
    - pandas_ml.snsaccessors.test
    - pandas_ml.test
    - pandas_ml.util
    - pandas_ml.xgboost
    - pandas_ml.xgboost.test
    
about:
  home: https://github.com/pandas-ml/pandas-ml
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'pandas, scikit-learn and xgboost integration'

  description: |
    pandas_ml is a package which integrates pandas, scikit-learn,
    xgboost into one package for easy handling of data and creation 
    of machine learning models.
  doc_url: http://pandas-ml.readthedocs.org/en/stable
  dev_url: https://github.com/pandas-ml/pandas-ml

extra:
  recipe-maintainers:
    - souravsingh
    - sinhrks
