travis:
  secure:
    BINSTAR_TOKEN: m0zzGbj4TgZFLpFLH7V4mtv+DxiDbcxO+wJUaZaCw+eX9hbx2vtzKQFuDQCdPB6By4LysMix+m9dmiP3dtUuGNJm0JLNVDWZKPv4AFC3rLsXDuJXhlVwCVrDyHB4Ja3gz/fw4SO53K3zaIS84ui+bNhcSHO1z1rYODyP68fbnfbWviPfUg5C0g+32pxZZ7xwp5UEOBgdiVidI1zezU1wva1rYXFm1Q2uNkd0XhY8woxa8VTRdahos8BM3KenAX7nHqiKe2c/UPup5T/y4xRSejBt9TmV0gK4Tin0+u+8OpVA2alcTJOabFGm6YKj/MQv/P/bejuTrRm6hVeK8x9cdasJDm7/F7Dg1sePORNC7GJz/1jYuj3MtvYro3nYzHvyQUFDkAXCPzx+4TZNVGFdccrkw6Ui1DqpYquaB21IKjrH1nHThh8Py9yKQ/JumPSzCO352HwavetWgucmT+coBsgcbJmROUvQ/9+wXmWwI+3bZPyAjljZJzd/XJGL4lUAO1/I/7iynlRUBjt5/qBiXW7zLvbzl3rJxplleqInicHkFo57HUVh0gbK2714k7AdE5YvgtFzziB1UEUAKU5j7QU7dROMz9ps+TyUswMBJisRVxBTQL9Uj/6ZuiVRjk1AQUk+FwNX0/wD+EEYy24WvSnBB02IWzzZ79th14vNPAk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
