appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: msSccVxSCQObblSwuFaduHDoGhOzWoue5sbiH0NrUL3qd6jUHP1TMl5Nrpz14GvBfXPrt+B7bmJIUeOGfK535JEKZHk6NBvd63JrIS56YjFnyl0VzA4Dqn5xGUUQwBjfCy33uZWHk+0DCqMfCkN3ydDA8jfF7Ird7WPtGoaDTAJ8OSNKzJrNMV8x8Rg3Xw6Qfbp/7akupS3QN4fYYsOYxD99603aT9oNmsNzF5hxx3qRRP23SKh3rjhyhZu1mMhUbbSYrV2tZzOgYr0wbGLUPNAuQlM2H/NyVcVblvEjx4cio+mIyAJ/4LSUsyL2XtDMoGnR/G6qAMKphOzlzw59V61hFRLGZudi30oe7FzrtpmiqbBEppRi4KGvcQWjSMA/PN27tVg0VIU8NrRPXKug6Iy4Rupz/spR52qstzy/r22cyiEESXTyqJKAAONbdFs9/BM0bhp0S3W2xVDqFAzZNDgp6bCE5pGVIMHI5bEi/Bf3ESt1GTzTxW1/1KSMAbRXlVjIhk4Q9zYKt+GvmffGgL5eVPp35h5qlTRNwEzm6I87oaWsPNkUqe9A68gI42SaFLuDFU09yHhTsJo51eENG5mbHWGEngHJSdFafR73pW2CYceDDTqsSoq1U/KWA2/AZMOanG54b+fmqOjd8VukzvBSrbLGcDEoKiHkLlzlXCY=}
